### ISSUE TITLE
What if it says : command not found ?

### ISSUE THREAD

**Issue by Daitan9** [AndronixApp/docs#3]
What if it says "command not found" when you vncserver-start ?

Thanks for help.

**Comment by icebarf** [comment]
Then there was an issue while you were installing your linux distro. This is due to internet issues where the script was not able to fetch Tiger VNC (actual name of the VNC App). My suggestions are either you uninstall and reinstall the whole distro this time having a good internet connection or just goto Tiger VNC docs and install it by yourself in your linux distro, If you have some experience in using Linux or have used it in past I suggest you to go with the latter as it fairly easy to setup Tiger VNC
